# Generated by Django 5.2.3 on 2025-06-23 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contact', models.IntegerField()),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('isOwner', models.BooleanField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=256)),
                ('barangay', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('postalCode', models.IntegerField()),
                ('outset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=64)),
                ('businessDescription', models.CharField(max_length=256)),
                ('businessContact', models.IntegerField()),
                ('businessLogo', models.ImageField(upload_to='business_logo/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('grams', models.IntegerField()),
                ('method', models.CharField(blank=True, choices=[('WET', 'Wet'), ('DRY', 'Dry'), ('HONEY', 'Honey')], null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='product_img')),
                ('image2', models.ImageField(upload_to='product_img')),
                ('image3', models.ImageField(upload_to='product_img')),
                ('image4', models.ImageField(upload_to='product_img')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
