# Generated by Django 5.2.3 on 2025-07-03 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=8, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('contact', models.BigIntegerField()),
                ('profilePhoto', models.ImageField(blank=True, default='profile_photo/generic_profile.jpg', null=True, upload_to='profile_photo/')),
                ('isOwner', models.BooleanField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=64)),
                ('businessDescription', models.CharField(max_length=256)),
                ('businessContact', models.BigIntegerField()),
                ('businessLogo', models.ImageField(blank=True, default='business_logo/generic_logo.jpg', null=True, upload_to='business_logo/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=256)),
                ('barangay', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('postalCode', models.IntegerField()),
                ('forCustomer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('forBusiness', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('price', models.BigIntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('grams', models.IntegerField()),
                ('mainImg', models.ImageField(blank=True, default='product_img/generic_product.jpg', null=True, upload_to='product_img')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOrdered', models.BooleanField(blank=True, default=0)),
                ('isDelivered', models.BooleanField(blank=True, default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('item', models.ManyToManyField(blank=True, to='api.product')),
            ],
        ),
    ]
