# Generated by Django 5.2.3 on 2025-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='forCustomer',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='address',
            name='forBusiness',
        ),
    ]
