# Generated by Django 5.2.3 on 2025-06-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='outset',
        ),
        migrations.AddField(
            model_name='address',
            name='forBusiness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
        ),
        migrations.AddField(
            model_name='address',
            name='forCustomer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
