# Generated by Django 5.2.3 on 2025-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_address_outset_address_forbusiness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessLogo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logo/'),
        ),
    ]
