# Generated by Django 5.2.3 on 2025-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_business_businesslogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='method',
            new_name='process',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, default='/generic_product', null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
    ]
