# Generated by Django 5.2.3 on 2025-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_method_product_process_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImg',
            field=models.ImageField(blank=True, default='/generic_product.jpeg', null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
    ]
