# Generated by Django 5.2.3 on 2025-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_mainimg_alter_images_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessLogo',
            field=models.ImageField(blank=True, default='/generic_logo.jpeg', null=True, upload_to='business_logo/'),
        ),
    ]
