# Generated by Django 5.2.3 on 2025-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_business_businesslogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessLogo',
            field=models.ImageField(blank=True, default='/generic_logo.jpg', null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImg',
            field=models.ImageField(blank=True, default='/generic_product.jpg', null=True, upload_to='product_img'),
        ),
    ]
