# Generated by Django 5.2.3 on 2025-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_business_businesslogo_alter_product_mainimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='/generic_profile.jpg', null=True, upload_to='profile_photo/'),
        ),
    ]
