# Generated by Django 5.2.3 on 2025-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_account_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessContact',
            field=models.BigIntegerField(),
        ),
    ]
