# Generated by Django 5.2.3 on 2025-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_account_contact_alter_business_businesscontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='profile_photo/generic_profile.jpg', null=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessLogo',
            field=models.ImageField(blank=True, default='business_logo/generic_logo.jpg', null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImg',
            field=models.ImageField(blank=True, default='product_img/generic_product.jpg', null=True, upload_to='product_img'),
        ),
    ]
