# Generated by Django 5.2.3 on 2025-06-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_profilephoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOrdered', models.BooleanField(blank=True, default=0)),
                ('isDelivered', models.BooleanField(blank=True, default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('items', models.ManyToManyField(blank=True, null=True, to='api.product')),
            ],
        ),
    ]
