# Generated by Django 5.2.3 on 2025-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_items_cart_item_account_age_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='process',
        ),
    ]
